"""document ingestion status

Revision ID: 02897036f6f6
Revises: 0fa0293fff3f
Create Date: 2026-01-25 10:57:03.994461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02897036f6f6'
down_revision: Union[str, Sequence[str], None] = '0fa0293fff3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(length=20), nullable=False, server_default="ready"))
    op.add_column('documents', sa.Column('num_chunks', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('ingest_error', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'ingest_error')
    op.drop_column('documents', 'num_chunks')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
